// apps/client/src/routes/project/(nodes)/country.svelte
<script module lang="ts">
  import { Link } from "lucide-svelte";
  import type { Country } from "~/gen/core";

  export function countryInit(name = ""): Country {
    return { name };
  }

  export { Link as URLIcon };
</script>

<script lang="ts">
  import BaseNode from "./base-node.svelte";

  let { id, data }: TypedNode<Country> = $props();

  const regionNames = new Intl.DisplayNames(["en"], { type: "region" });

  const country = data.name;

  let countryFull = $state(country);
  try {
    countryFull = regionNames.of(country) ?? "";
  } catch (e) {}
</script>

<BaseNode {id}>
  {#snippet opts()}
    <button>
      Edit
    </button>
  {/snippet}

  <div class={`
    rounded-full p-0 w-[160px] aspect-square fib fis flex justify-center
    ${"fi-" + country.toLowerCase()}
  `}>
    <h2 class="dark rounded-lg !h-fit text-center py-1 px-2">
      {countryFull}
    </h2>
  </div>
</BaseNode>

// apps/client/src/nodes/country.tsx
import { Flag } from "lucide-react";
import type { Country } from "~/gen/core";
import { cn } from "~/utils";
import { BaseNode, createNode } from "./utils";

const regionNames = new Intl.DisplayNames(["en"], { type: "region" });

function countryInit(name = "") {
  return { name };
}

export const country = createNode<Country, typeof countryInit>({
  type: "country",
  icon: <Flag width={17} />,
  initFn: countryInit,
  graphNode(props) {
    const country = props.data.name;

    let countryFull = country;
    try {
      countryFull = regionNames.of(country!) ?? "";
    } catch (e) {}

    return (
      <BaseNode
        node={props}
        className={cn(
          "rounded-full p-0 min-w-[160px] aspect-square fib fis items-center",
          "fi-" + country?.toLocaleLowerCase(),
        )}
      >
        <h3 className="layer-dark rounded-lg !w-fit text-center font-semibold py-1 px-2">
          {countryFull}
        </h3>
      </BaseNode>
    );
  },
});
