// apps/client/src/nodes/nickname.tsx
import { AtSign } from "lucide-react";
import {
  ContextMenuItem,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
} from "~/components/ui/context-menu";
import { Input } from "~/components/ui/input";
import type { Nickname } from "~/gen/core";
import { useSherlockSearchMutation } from "~/tools/sherlock/tauri-api";
import { SearchExact } from "./text";
import { BaseNode, createNode } from "./utils";

function nicknameInit(nickname = "") {
  return { nickname };
}

export const nickname = createNode<Nickname, typeof nicknameInit>({
  type: "nickname",
  icon: <AtSign width={18} />,
  initFn: nicknameInit,
  graphNode(props) {
    const { updateNode } = props.useReactFlow();
    const sherlockSearch = useSherlockSearchMutation(props.data.nickname);

    return (
      <BaseNode
        node={props}
        className="w-[200px]"
        actions={[
          <ContextMenuSub key={0}>
            <ContextMenuSubTrigger disabled={!props.data.nickname}>
              Sherlock
            </ContextMenuSubTrigger>
            <ContextMenuSubContent>
              <ContextMenuItem onClick={() => sherlockSearch.mutate()}>
                Search nickname
              </ContextMenuItem>
            </ContextMenuSubContent>
          </ContextMenuSub>,

          <SearchExact key={1} text={props.data.nickname} />,
        ]}
      >
        <h2 className="font-semibold flex gap-2">
          <AtSign width={18} />
          NICKNAME
        </h2>
        <Input
          autoComplete="disabled-auto"
          defaultValue={props.data.nickname}
          onChange={(evt) => {
            updateNode(props.id, {
              ...props,
              data: { ...props.data, nickname: evt.target.value },
            });
          }}
        />
      </BaseNode>
    );
  },
});

// apps/client/src/routes/project/(nodes)/nickname.svelte
<script module lang="ts">
  import { AtSign } from "lucide-svelte";
  import type { Nickname } from "~/gen/core";
  import SherlockLogo from "~/icons/sherlock-logo.png";

  export function nicknameInit(nickname = ""): Nickname {
    return { nickname };
  }

  export { AtSign as NicknameIcon };
</script>

<script lang="ts">
  import { Sherlock } from "$lib/tools/sherlock/tauri-api";
  import { nodes } from "../store";
  import { BaseNode, SearchText } from "./(utils)";

  let { id, data }: TypedNode<Nickname> = $props();

  let sherlockSearch = Sherlock.searchNicknameMut();

  let nickname = $state(data.nickname);

  $effect(() => {
    nodes.update((old) => old.map((n) => n.id !== id ? n : {
      ...n,
      data: { ...n.data, nickname },
    }));
  });
</script>

<BaseNode {id}>
  {#snippet opts()}
    <SearchText text={nickname} />

    <button
      disabled={!nickname}
      onclick={() => $sherlockSearch.mutate(nickname)}
      class="disabled:opacity-75"
    >
      <img src={SherlockLogo} alt="Sherlock Logo" class="w-[29px]" />
      Sherlock Search
    </button>
  {/snippet}

  <div class="w-64 dark rounded-lg py-2 px-3 flexcol gap-2">
    <div class="flex gap-2 items-center">
      <AtSign />
      <input
        bind:value={nickname}
        placeholder="NICKNAME"
        class="w-full dark nowheel nodrag px-1 border border-2 border-gray-800 rounded-md"
      />
    </div>
  </div>
</BaseNode>
