// apps/client/src/app/(dashboard)/(projects)/_project-card.tsx
import { FileArchive, Pencil, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from "~/components/ui/context-menu";
import { Dialog, DialogContent, DialogTrigger } from "~/components/ui/dialog";
import type { ProjectMeta } from "~/gen/core";
import { useProject } from "~/projects/store";
import { cn } from "~/utils";
import { ArchiveProject } from "./_archive-project";
import { DeleteProject } from "./_delete-project";
import { EditDialog } from "./_edit-project";

function ProjectCtxMenu(
  props: React.PropsWithChildren<{ project: ProjectMeta }>,
) {
  const openProject = useProject((state) => state.openProject);
  const router = useRouter();
  const [dialogContent, setDialogContent] = useState<React.ReactNode | null>(
    null,
  );
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <ContextMenu>
        <ContextMenuTrigger
          onDoubleClick={() => openProject(props.project, router)}
        >
          {props.children}
        </ContextMenuTrigger>
        <ContextMenuContent className="font-semibold">
          <DialogTrigger
            onClick={() =>
              setDialogContent(
                <EditDialog
                  {...props.project}
                  closeDialog={() => setOpen(false)}
                />,
              )
            }
            className="w-full *:w-full *:flex *:gap-2"
          >
            <ContextMenuItem>
              <Pencil width={16} />
              Edit
            </ContextMenuItem>
          </DialogTrigger>

          <ContextMenuSeparator />

          <DialogTrigger
            onClick={() =>
              setDialogContent(<ArchiveProject {...props.project} />)
            }
            className="w-full *:w-full *:flex *:gap-2 text-yellow-600"
          >
            <ContextMenuItem>
              <FileArchive size={18} />
              {props.project.archived ? "Unarchive" : "Archive"}
            </ContextMenuItem>
          </DialogTrigger>

          <DialogTrigger
            onClick={() =>
              setDialogContent(<DeleteProject {...props.project} />)
            }
            className="w-full *:w-full *:flex *:gap-2 text-red-600"
          >
            <ContextMenuItem>
              <Trash2 size={18} />
              Delete
            </ContextMenuItem>
          </DialogTrigger>
        </ContextMenuContent>
      </ContextMenu>
      <DialogContent aria-describedby={undefined}>
        {dialogContent}
      </DialogContent>
    </Dialog>
  );
}

export function ProjectCard(props: ProjectMeta) {
  return (
    <ProjectCtxMenu project={props}>
      <article className="layer-dark p-3 rounded-lg cursor-pointer select-none">
        <h1
          className={cn(
            "text-lg font-bold line-clamp-1",
            props.archived && "opacity-60",
          )}
        >
          {props.name}
        </h1>
        <p
          className={cn(
            "line-clamp-3 h-[3lh] break-words",
            props.archived && "opacity-60",
          )}
        >
          {props.desc}
        </p>

        <div className="flex justify-between items-center pt-3">
          <time className="opacity-75">
            {new Date(Number(props.created_at)).toDateString()}
          </time>
        </div>
      </article>
    </ProjectCtxMenu>
  );
}

// apps/client/src/routes/(hub)/(projects)/project-card.svelte
<script lang="ts">
  import { CtxMenu, Btn, Dialog } from "$lib/components";
  import { deleteProject, editProject } from "$lib/projects/tauri-api";
  import { FileArchive, Pencil, Trash2 } from "lucide-svelte";
  import type { ProjectMeta } from "~/gen/core";
  import { changeOpenProject } from "$lib/projects/store";

  let prj: ProjectMeta = $props();

  let detelePrj = deleteProject();
  let editPrj = editProject();
</script>

<CtxMenu>
  {#snippet options()}
    <button onclick={() => console.log(prj.name)}>
      <Pencil size={20} />
      Edit
    </button>

    <button class="text-yellow-600" onclick={() => $editPrj.mutate({ ...prj, archived: !prj.archived })}>
      <FileArchive size={20} />
      {prj.archived ? "Unarchive" : "Archive"}
    </button>

    <Dialog title="DELETE PROJECT">
      {#snippet trigger()}
        <button class="text-red-600">
          <Trash2 size={20} />
          Delete
        </button>
      {/snippet}

      {#snippet options()}
        <Btn
          class="bg-red-600 text-white"
          onclick={() => $detelePrj.mutate(prj.id)}
        >
          <Trash2 size={18} />
          Delete
        </Btn>
      {/snippet}

      <p class="opacity-70">Are you sure you want to delete this project?</p>
    </Dialog>
  {/snippet}

  <article
    ondblclick={() => changeOpenProject(prj)}
    class="dark p-3 rounded-lg cursor-pointer select-none"
  >
    <h1 class={`line-clamp-1 ${prj.archived ? "opacity-60" : ""}`}>
      {prj.name}
    </h1>
    <p class={`line-clamp-3 h-[3lh] break-words ${prj.archived ? "opacity-60" : ""}`}>
      {prj.desc}
    </p>

    <div class="flex justify-between items-center pt-3">
      <time class="opacity-75">
        {new Date(Number(prj.created_at)).toDateString()}
      </time>
    </div>
  </article>
</CtxMenu>
