// apps/client/src/lib/components/nav-link.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import type { HTMLAnchorAttributes } from "svelte/elements";

  let { children, ...props }: Omit<HTMLAnchorAttributes, "aria-current"> & {
    aliases?: string[];
  } = $props();
</script>

<a
  aria-current={[props.href, ...(props.aliases ?? [])].includes($page.url.pathname) && "page"}
  {...props}
>
  {@render children?.()}
</a>

// apps/client/src/components/nav-link.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

export function NavLink(
  props: Omit<React.ComponentProps<typeof Link>, "aria-current"> & {
    aliases?: string[];
  },
) {
  const pathname = usePathname();
  const propsPath = (
    typeof props.href === "string" ? props.href : props.href.pathname
  )?.split("?")[0];

  const isActive = [propsPath, ...(props.aliases ?? [])].includes(pathname);

  return <Link aria-current={isActive && "page"} {...props} />;
}
