// apps/client/src/tools/sherlock/config.tsx
"use client";

import {
  useSherlockInstallMutation,
  useSherlockStatusQuery,
} from "~/tools/sherlock/tauri-api";
import { PythonWarning, ToolSection } from "../tool-section";

export function Sherlock() {
  const installSherlock = useSherlockInstallMutation();
  const sherlockInstalled = !!useSherlockStatusQuery().data;

  return (
    <ToolSection
      title="Sherlock (Nickname search engine)"
      link="https://github.com/sherlock-project/sherlock"
      downloadMut={installSherlock}
      installed={sherlockInstalled}
    >
      <PythonWarning />
    </ToolSection>
  );
}

// apps/client/src/lib/tools/sherlock/config.svelte
<script lang="ts">
  import PythonWarn from "../python-warn.svelte";
  import Tool from "../tool.svelte";
  import { Sherlock } from "./tauri-api";
</script>

<Tool
  name="Sherlock (Nickname search engine)"
  url="https://github.com/sherlock-project/sherlock"
  checkQuery={Sherlock.statusQuery}
  installMut={Sherlock.installMut}
>
  <PythonWarn />
</Tool>
