// apps/client/src/routes/client-init.svelte
<script lang="ts">
  import { dev } from "$app/environment";
  import PrefetchTools from "$lib/tools/prefetch.svelte";
  import { QueryClient, QueryClientProvider } from "@tanstack/svelte-query";
  import type { Snippet } from "svelte";

  let { children }: { children: Snippet } = $props();
</script>

<!-- disable some browser features in prod so app feels more native -->
<svelte:window
  oncontextmenu={(evt) => evt.preventDefault()}
  onkeydown={(e) => {
    if (dev) return;

    if (["r", "f"].includes(e.key.toLowerCase()) && (e.ctrlKey || e.metaKey))
      e.preventDefault();

    if (e.key === "F5") e.preventDefault();
  }}
/>

<QueryClientProvider client={new QueryClient()}>
  <PrefetchTools />

  {@render children()}
</QueryClientProvider>

// apps/client/src/app/_client-init.tsx
"use client";

import { useInfogaStatusQuery } from "~/tools/phone_infoga/tauri-api";
import { useSherlockStatusQuery } from "~/tools/sherlock/tauri-api";

// disable some browser features in prod so app feels more native
if (process.env.NODE_ENV !== "development") {
  window.addEventListener("keydown", (e) => {
    if (["r", "f"].includes(e.key.toLowerCase()) && (e.ctrlKey || e.metaKey))
      e.preventDefault();

    if (e.key === "F5") e.preventDefault();
  });

  window.addEventListener("contextmenu", (e) => e.preventDefault());
}

export default function AppInit() {
  // prefetch tools
  useInfogaStatusQuery();
  useSherlockStatusQuery();

  return null;
}
