// apps/client/src/lib/tools/phone-infoga/config.svelte
<script lang="ts">
  import { browse } from "$lib/utils";
  import Tool from "../tool.svelte";
  import { Infoga } from "./tauri-api";
  import {
    numverifyKey, l_numverifyKey,
    googleCSECX, l_googleCSECX,
    googleApiKey, l_googleApiKey,
    CSEMaxResults, l_CSEMaxResults,
  } from "./store";
</script>

<Tool
  name="PhoneInfoga (Phone number lookup)"
  url="https://github.com/sundowndev/phoneinfoga"
  checkQuery={Infoga.statusQuery}
  installMut={Infoga.installMut}
>
  <h2>Optional Settings</h2>
  <button
    class="opacity-75 hover:opacity-100"
    onclick={(e) => browse(e.currentTarget.textContent!)}
  >
    https://sundowndev.github.io/phoneinfoga/getting-started/scanners/
  </button>

  <h3 class="pt-4 pb-0.5">Numverify API (free 100 reqs/month; no CC required)</h3>
  <input
    placeholder={l_numverifyKey}
    value={$numverifyKey}
    onchange={(e) => numverifyKey.set(e.currentTarget.value)}
    class="dark px-3 py-2 rounded-md border border-2 border-gray-800 w-full"
  />

  <h3 class="pt-2 pb-0.5">Google CSE CX</h3>
  <input
    placeholder={l_googleCSECX}
    value={$googleCSECX}
    onchange={(e) => googleCSECX.set(e.currentTarget.value)}
    class="dark px-3 py-2 rounded-md border border-2 border-gray-800 w-full"
  />

  <h3 class="pt-2 pb-0.5">Google API Key</h3>
  <input
    placeholder={l_googleApiKey}
    value={$googleApiKey}
    onchange={(e) => googleApiKey.set(e.currentTarget.value)}
    class="dark px-3 py-2 rounded-md border border-2 border-gray-800 w-full"
  />

  <h3 class="pt-2 pb-0.5">CSE Max Results</h3>
  <input
    placeholder={l_CSEMaxResults}
    value={$CSEMaxResults}
    onchange={(e) => CSEMaxResults.set(Number(e.currentTarget.value))}
    class="dark px-3 py-2 rounded-md border border-2 border-gray-800 w-full"
  />
</Tool>

// apps/client/src/tools/phone_infoga/config.tsx
"use client";

import { ExternalLink } from "~/components/links";
import { Input } from "~/components/ui/input";
import { ToolSection } from "../tool-section";
import {
  googleApiKeyStr,
  googleCSECXStr,
  googleCSEMaxResultsStr,
  numverifyKeyStr,
  useInfogaEnvs,
} from "./store";
import { useInfogaInstallMutation, useInfogaStatusQuery } from "./tauri-api";

export function PhoneInfoga() {
  const installInfoga = useInfogaInstallMutation();
  const infogaInstalled = !!useInfogaStatusQuery().data;
  const infogaEnvs = useInfogaEnvs();

  return (
    <ToolSection
      title="PhoneInfoga (Phone number lookup)"
      link="https://github.com/sundowndev/phoneinfoga"
      downloadMut={installInfoga}
      installed={infogaInstalled}
    >
      <section className="flexcol gap-4">
        <div>
          <h2 className="text-xl font-semibold">Optional settings</h2>
          <ExternalLink
            className="text-base text-white/75 hover:text-white"
            href="https://sundowndev.github.io/phoneinfoga/getting-started/scanners/"
          >
            https://sundowndev.github.io/phoneinfoga/getting-started/scanners/
          </ExternalLink>
        </div>

        <div className="flexcol gap-2">
          <h3 className="text-base font-semibold">
            Numverify API (free 100 reqs/month; no cc required)
          </h3>
          <Input
            placeholder={numverifyKeyStr}
            defaultValue={infogaEnvs.numverifyKey || ""}
            onChange={(e) => infogaEnvs.setNumverifyKey(e.target.value)}
          />
        </div>

        <div className="flexcol gap-2">
          <h3 className="text-base font-semibold">Google CSE</h3>
          <Input
            placeholder={googleCSECXStr}
            defaultValue={infogaEnvs.googleCSECX || ""}
            onChange={(e) => infogaEnvs.setGoogleCSECX(e.target.value)}
          />
          <Input
            placeholder={googleApiKeyStr}
            defaultValue={infogaEnvs.googleApiKey || ""}
            onChange={(e) => infogaEnvs.setGoogleApiKey(e.target.value)}
          />

          <span>{googleCSEMaxResultsStr} (default: 10)</span>
          <Input
            placeholder={googleCSEMaxResultsStr}
            defaultValue={infogaEnvs.googleCSEMaxResults || ""}
            onChange={(e) =>
              infogaEnvs.setGoogleCSEMaxResults(Number(e.target.value))
            }
          />
        </div>
      </section>
    </ToolSection>
  );
}
