// apps/client/src/app/(dashboard)/tools/page.tsx
import { BellingcatTg } from "~/tools/bellingcat_tg/config";
import { PhoneInfoga } from "~/tools/phone_infoga/config";
import { Sherlock } from "~/tools/sherlock/config";

export default function ToolsPage() {
  return (
    <section className="flexcol gap-2">
      <PhoneInfoga />
      <BellingcatTg />
      <Sherlock />
    </section>
  );
}

// apps/client/src/routes/(hub)/tools/+page.svelte
<script lang="ts">
  import SherlockConfig from "$lib/tools/sherlock/config.svelte";
  import InfogaConfig from "$lib/tools/phone-infoga/config.svelte";
  import BellingCatTgConfig from "$lib/tools/bellingcat-tg/config.svelte";
</script>

<section class="flexcol gap-2">
  <SherlockConfig />
  <InfogaConfig />
  <BellingCatTgConfig />
</section>
