// apps/client/src/routes/(hub)/(projects)/+page.svelte
<script lang="ts">
  import { Select } from "$lib/components";
  import CreateProject from "./create-project.svelte";
  import { Search } from "lucide-svelte";
  import ProjectCard from "./project-card.svelte";
  import { getProjects } from "$lib/projects/tauri-api";

  let prjFilter = $state<string>();
  let prjSearch = $state<string>();

  let projects = getProjects();
</script>

<menu class="sticky left-0 top-0 dark p-3 rounded-lg flex gap-3 z-[5] border border-2">
  <CreateProject />

  <div class="flex-1 light flex rounded-lg overflow-hidden gap-3 items-center px-3">
    <Search />
    <input
      class="flex-1 focus:outline-0 text-lg"
      placeholder="Search projects"
      bind:value={prjSearch}
    />
  </div>

  <Select initialText="Filter projects" bind:value={prjFilter}>
    <option value="all">All</option>
    <option value="archived">Archived</option>
    <option value="active">Active</option>
  </Select>
</menu>

<section class="grid gap-3 pt-3 grid-cols-2 xl:grid-cols-3">
  {#if $projects.isSuccess}
    {#each $projects.data.filter((prj) => {
      if (prjFilter === "archived") return prj.archived;
      if (prjFilter === "active") return !prj.archived;

      return true; // ProjectFilter.All
    }).sort((a, b) => {
      if (a.archived !== b.archived) return a.archived ? 1 : -1;
      return Number(b.created_at - a.created_at);
    }) as prj}
      <ProjectCard {...prj} /> 
    {/each}
  {:else if $projects.isError}
    <p class="text-red-500 font-semibold">
      {$projects.error.message}
    </p>
  {/if}
</section>

// apps/client/src/app/(dashboard)/(projects)/page.tsx
"use client";

import { useState } from "react";
import { useProjectsQuery } from "~/projects/tauri-api";
import { CreateProject } from "./_create-project";
import { ProjectCard } from "./_project-card";
import { ProjectFilter, ProjectFilterSelect } from "./_project-filter-select";
import { ProjectsSearch } from "./_projects-search";

export default function ProjectsPage() {
  const [projectFilter, setProjectFilter] = useState(ProjectFilter.All);
  const projects = useProjectsQuery();

  if (projects.isError) {
    console.log(projects.error);
  }

  const filteredProjects = projects.data
    ?.filter((project) => {
      if (projectFilter === ProjectFilter.Archived) return project.archived;

      if (projectFilter === ProjectFilter.Active) return !project.archived;

      // ProjectFilter.All
      return true;
    })
    .sort((a, b) => {
      if (a.archived !== b.archived) return a.archived ? 1 : -1;
      return Number(b.created_at - a.created_at);
    });

  return (
    <>
      <section className="sticky left-0 top-0 bg-black p-3 rounded-lg flex justify-between gap-3 z-[5] border border-2">
        <CreateProject />

        <ProjectsSearch />
        <ProjectFilterSelect
          filter={projectFilter}
          setFilter={setProjectFilter}
        />
      </section>

      <section className="grid gap-3 pt-3 grid-cols-2 xl:grid-cols-3">
        {filteredProjects?.map((project) => (
          <ProjectCard key={project.id} {...project} />
        ))}
      </section>
    </>
  );
}
